// lib/app/secrets.dart
//
// ─────────────────────────────────────────────────────────────────────────────
// HOW THIS WORKS
// ─────────────────────────────────────────────────────────────────────────────
//
// The API token is NOT stored as a plaintext constant.  A plaintext secret can
// be trivially extracted from any published APK/IPA using `strings`, jadx, or
// apktool regardless of whether it came from source code or a .env file.
//
// Instead we use a two-layer approach:
//
//   Layer 1 – Build-time injection via --dart-define (preferred in dev / CI):
//     The token is passed at compile time and never touches the repo.
//
//   Layer 2 – XOR obfuscation at runtime (release builds):
//     If no --dart-define is present the token is reconstructed at runtime by
//     XOR-ing a pre-computed byte table with a compile-time key scattered in
//     code.  Combined with Flutter's --obfuscate flag this prevents plaintext
//     string extraction from the binary.
//
// ─────────────────────────────────────────────────────────────────────────────
// BUILDING / RUNNING
// ─────────────────────────────────────────────────────────────────────────────
//
//   Dev:
//     flutter run --dart-define=XDEVH_TOKEN=xdv_...
//
//   Release (recommended — both layers active):
//     flutter build apk \
//       --obfuscate \
//       --split-debug-info=symbols/ \
//       --dart-define=XDEVH_TOKEN=xdv_...
//
//   CI/CD:
//     Set XDEVH_TOKEN as a secret env var, then:
//     flutter build apk --obfuscate ... --dart-define=XDEVH_TOKEN=$XDEVH_TOKEN
//
// ─────────────────────────────────────────────────────────────────────────────

// ignore_for_file: constant_identifier_names

/// XOR key — 32 bytes.
/// Changing this requires re-generating _T with the script at scripts/gen_secrets.py
const List<int> _K = [
  0x56, 0x4F, 0x49, 0x44, 0x5F, 0x53, 0x50, 0x41, // VOID_SPA
  0x43, 0x45, 0x5F, 0x4B, 0x45, 0x59, 0x5F, 0x32, // CE_KEY_2
  0x30, 0x32, 0x35, 0x5F, 0x58, 0x44, 0x56, 0x5F, // 025_XDV_
  0x53, 0x45, 0x43, 0x52, 0x45, 0x54, 0x21, 0x40, // SECRET!@
];

/// Obfuscated token bytes.
/// Generated by: scripts/gen_secrets.py  (token XOR _K, cycling)
const List<int> _T = [
  0x2E, 0x2B, 0x3F, 0x1B, 0x68, 0x6B, 0x36, 0x77,
  0x7B, 0x21, 0x3E, 0x7D, 0x26, 0x6E, 0x3D, 0x04,
  0x05, 0x50, 0x00, 0x3B, 0x6B, 0x70, 0x32, 0x6A,
  0x30, 0x20, 0x7B, 0x34, 0x70, 0x61, 0x47, 0x26,
  0x6F, 0x2A, 0x70, 0x73, 0x6D, 0x65, 0x63, 0x23,
  0x71, 0x27, 0x3C, 0x2A, 0x70, 0x61, 0x6E, 0x07,
  0x00, 0x00, 0x56, 0x6D,
];

/// Cached decoded value — decoded once, reused on subsequent calls.
String? _cachedToken;

/// Returns the x.devh.in API bearer token.
///
/// Priority:
///   1. `--dart-define=XDEVH_TOKEN=...` value (set at build time, not in repo)
///   2. XOR-decoded embedded bytes  (fallback for release builds)
String get xDevhToken {
  if (_cachedToken != null) return _cachedToken!;

  // Layer 1: compile-time injection (preferred)
  const injected = String.fromEnvironment('XDEVH_TOKEN');
  if (injected.isNotEmpty) {
    _cachedToken = injected;
    return _cachedToken!;
  }

  // Layer 2: decode from obfuscated byte table
  final buf = StringBuffer();
  for (var i = 0; i < _T.length; i++) {
    buf.writeCharCode(_T[i] ^ _K[i % _K.length]);
  }
  _cachedToken = buf.toString();
  return _cachedToken!;
}
